name: dsd-carroarmato0 # you probably want to 'snapcraft register <name>'
base: core18 # the base snap is the execution environment for this snap
version: '1.7.0-dev' # just for humans, typically '1.2+git' or '1.3.2'
summary: Digital Speech Decoder # 79 char long summary
description: |
  DSD is able to decode several digital voice formats from 
  discriminator tap audio and synthesize the decoded speech.
  Speech synthesis requires mbelib, which is a separate package.

grade: stable # must be 'stable' to release into candidate/stable channels
confinement: strict # use 'strict' once you have the right plugs and slots

apps:
  dsd:
    command: bin/dsd
    plugs:
      - audio-playback
      - pulseaudio
      - alsa

parts:
  mbelib:
    plugin: cmake
    source: https://github.com/szechyjs/mbelib.git
  dsd:
    plugin: cmake
    source: https://github.com/szechyjs/dsd.git
    after: [mbelib]
    build-packages:
      - libitpp-dev
      - libsndfile1-dev
    stage-packages:
      - libfftw3-double3
      - libflac8
      - libgfortran4
      - libgomp1
      - libitpp8v5
      - libogg0
      - libquadmath0
      - libsndfile1
      - libvorbis0a
      - libvorbisenc2
      - libblas3